[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Mark Oborne <markoborne1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
packed_simd_2 = "0.3.4"